### PR TITLE
Add dialout permissions instructions to no-port

### PR DESCRIPTION
**Pull request by SirGoodenough**
I didn't have a way to test the code or build this.  
Please do a code review.

This adds a message for Linux users having problems getting the WebTools to grab a port.

### CODE REVIEW

**Comment by balloob** [comment]
We should only show this message if we know that the user is using a Linux platform. You can test for that using `/Linux/.test(navigator.platform)`

**Comment by SirGoodenough** [comment]
And likewise we should only sendr windows messages if the user is on a windows platform, etc.
I personally don't know how to pull that off.
If there is someone that can do this now, great. 
Otherwise what's one more message in that stack?

**Comment by RosemaryOrchard** [comment]
There is an alternative: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/platform

**Comment by SirGoodenough** [comment]
Thanks for the link.  I read that over and still have no clue what to do with it.
I'm looking for someone that can pull this off.

**Review by balloob — APPROVED** [review]
Thanks!

**Pull request merged**
