### PR TITLE
v4.0.0 - Next Gen

### PR DESCRIPTION
**Pull request by balloob**
This is the next generation of the ESP Web Tools.

Marked as draft as it's not 100% done yet.

What's new:

- Everything now renders inside a dialog. Makes it easier to embed in documentation.
- The used custom components are registered with a unique ESP Web Tools prefix (`ewt-`) to not clash with already loaded web components.
- **Breaking change** The "improv" build property is no longer supported. Improv over BLE is now replaced by the new [Improv over Serial](https://github.com/improv-wifi/website/pull/7) which can be automatically detected. Improv over Serial is a serial-based version that is low overhead.
- **Breaking change** The manifest is now required to have a `version` attribute. The `name` and `version` in the manifest are compared with the response values of Improv over Serial `info` command to detect if it is the same firmware and/or update is available.
- If device supports Improv over Serial, a user can re-configure Wi-Fi, update the device (=no erasing) and navigate to the configuration URL even if not installed via ESP Web Tools:

https://user-images.githubusercontent.com/1444314/140466557-7746aaf7-232c-4213-8b0f-3317439b2da1.mp4

- If device is detected to not support Improv, it launches the installation wizard (like before). (wizard = erase/install/provision/go to device URL).
- If device supports Improv but is a different firmware than specified in the manifest, dashboard is shown except that the update button is replaced with an install button.
- Added option to look at the device logs, send serial commands and reset device

Tagging some people that are currently using ESP Web Tools to get some feedback: @Aircoookie @TD-er @arendst

### CODE REVIEW

**Comment by TD-er** [comment]
It would be really nice to have some terminal option right after flashing.
Especially a terminal which allows the user to type some commands to be sent to the node.

This way the initial deployment could be a lot simpler and also the user may have some feedback on what is happening on the node.

**Comment by Jason2866** [comment]
+1 for the suggestion of @TD-er  We have a Flasher app for Tasmota which do have this feature. Many people just use this flasher because the see whats happens after flash/reboot.

**Comment by balloob** [comment]
I've added a console. I am still having some issues with the rendering and would love some help. My terminal knowledge is limited. I have reused the terminal output renderer from the ESPHome dashboard but as you can see in the video, something is off.

Reading logic: https://github.com/esphome/esp-web-tools/blob/v2/src/components/ewt-console.ts#L167-L175
Console logic: https://github.com/esphome/esp-web-tools/blob/v2/src/util/console-color.ts

Without Improv:

image

With Improv:

https://user-images.githubusercontent.com/1444314/140548336-edab64e9-9d93-4260-9c65-c8e148059b6c.mp4

**Comment by balloob** [comment]
Alright this branch is up to date now with all the changes I want to make. Any further features (like using chipFamily from Improv Serial) will be out of scope for this PR.

**Comment by balloob** [comment]
https://user-images.githubusercontent.com/1444314/140884183-2f78276f-0e5c-4817-b574-5a4fff6fde9e.mp4

**Pull request merged**
