### PR TITLE
Fix casing of ESPLoader.js

### PR DESCRIPTION
**Pull request by amandel**
- fixes https://github.com/esphome/esp-web-tools/issues/270
- depending on file systems build did work or not

### CODE REVIEW

**Comment by balloob** [comment]
Ha ooff nice catch. That one bites me like once a year 😓

**Comment by amandel** [comment]
Glad I could help.

**Comment by dumbasPL** [comment]
@amandel when will this be released? This is a bug fix so just a patch version bump should be fine.

**Comment by amandel** [comment]
This is a question for @balloob.

**Pull request merged**
